kind: IoTConfig
apiVersion: iot.enmasse.io/v1alpha1
metadata:
  namespace: enmasse-infra
  name: default
spec:
  services:
    deviceRegistry:
      file:
        numberOfDevicesPerTenant: 100000
  adapters:
    mqtt:
      endpoint:
        secretNameStrategy:
          secretName: iot-mqtt-adapter-tls
    sigfox:
      enabled: false
    lorawan:
      enabled: false
