apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: simulator
  namespace: iot-simulator
spec:
  channel: alpha
  name: iot-simulator
  source: community-operators
  sourceNamespace: openshift-marketplace
